/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

/**
 *
 * @author melissa
 */
public class VentanaInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicio.class.getName());

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioIntro = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        sesion = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        introUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        password = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        enviar = new javax.swing.JButton();
        introPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuarioIntro.setBackground(new java.awt.Color(255, 255, 255));
        usuarioIntro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        usuarioIntro.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        city.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/city.png"))); // NOI18N
        usuarioIntro.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 0, -1, -1));

        sesion.setFont(new java.awt.Font("Nimbus Sans Narrow", 1, 24)); // NOI18N
        sesion.setForeground(new java.awt.Color(0, 0, 0));
        sesion.setText("Inicio de sesión");
        usuarioIntro.add(sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        usuario.setFont(new java.awt.Font("Nimbus Sans Narrow", 1, 18)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 0, 0));
        usuario.setText("Usuario");
        usuarioIntro.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        introUsuario.setBackground(new java.awt.Color(255, 255, 255));
        introUsuario.setFont(new java.awt.Font("Nimbus Sans Narrow", 0, 15)); // NOI18N
        introUsuario.setForeground(new java.awt.Color(153, 153, 153));
        introUsuario.setText("Introduce tu usuario");
        introUsuario.setBorder(null);
        usuarioIntro.add(introUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 270, -1));
        usuarioIntro.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 280, 10));

        password.setFont(new java.awt.Font("Nimbus Sans Narrow", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setText("Contraseña");
        usuarioIntro.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        usuarioIntro.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 280, 10));

        enviar.setBackground(new java.awt.Color(81, 202, 237));
        enviar.setForeground(new java.awt.Color(0, 0, 0));
        enviar.setText("Enviar");
        usuarioIntro.add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        introPassword.setBackground(new java.awt.Color(255, 255, 255));
        introPassword.setText("asdasd");
        introPassword.setBorder(null);
        usuarioIntro.add(introPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuarioIntro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuarioIntro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel city;
    private javax.swing.JButton enviar;
    private javax.swing.JPasswordField introPassword;
    private javax.swing.JTextField introUsuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel password;
    private javax.swing.JLabel sesion;
    private javax.swing.JLabel usuario;
    private javax.swing.JPanel usuarioIntro;
    // End of variables declaration//GEN-END:variables
}
